name: 'mfp-client'
version: 0.0.1
description: A simple frontend for mf-proto.
#author: Bodie Solomon <bodie@synapsegarden.net>
#homepage: https://github.com/synapse-garden

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter
